import "dotenv/config";
import { createClient } from "@supabase/supabase-js";

async function setup() {
  const supabaseUrl = process.env.VITE_SUPABASE_URL;
  const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.VITE_SUPABASE_ANON_KEY;
  
  if (!supabaseUrl || !supabaseKey) {
    console.error("Missing Supabase credentials");
    return;
  }

  const supabase = createClient(supabaseUrl, supabaseKey);

  console.log("Checking for iconic_codes table...");

  // We can't easily create tables via the JS client without the 'pg' extension or similar,
  // but we can try to insert and see if it fails.
  // Best practice is to provide the SQL to the user.

  const initialCodes = [
    "ICONIC-OG-10-ABC",
    "ICONIC-OG-15-XYZ",
    "ICONIC-OG-20-LMN",
    "ICONIC-OG-STUDENT-55",
    "ICONIC-OG-VIP-99",
    "ICONIC-OG-Bargain-01",
    "ICONIC-OG-Bargain-02",
    "ICONIC-OG-Bargain-03",
    "ICONIC-OG-Bargain-04",
    "ICONIC-OG-Bargain-05"
  ];

  console.log("Attempting to seed initial codes...");
  
  for (const code of initialCodes) {
    const { error } = await supabase
      .from('iconic_codes')
      .upsert({ code }, { onConflict: 'code' });
    
    if (error) {
      if (error.code === '42P01') {
        console.error("\n[ERROR] Table 'iconic_codes' does not exist in your Supabase database.");
        console.log("\nPlease run the following SQL in your Supabase SQL Editor first:\n");
        console.log(`
CREATE TABLE iconic_codes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE NOT NULL,
  claimed_by UUID REFERENCES auth.users(id),
  claimed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE iconic_codes ENABLE ROW LEVEL SECURITY;

-- Allow users to read their own claimed codes
CREATE POLICY "Users can view their own claimed codes" 
ON iconic_codes FOR SELECT 
USING (auth.uid() = claimed_by);
        `);
        return;
      }
      console.error(`Error seeding code ${code}:`, error.message);
    } else {
      console.log(`Successfully seeded/verified code: ${code}`);
    }
  }

  console.log("\nSetup complete! OG users can now claim these codes.");
}

setup();
